# Generated by Django 4.1.6 on 2023-02-02 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='added_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='report',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
